project:
  type: website
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!projects"
  resources:
    - projects/dsan-5000/_site
    - projects/dsan-5100/_site

website:
  title: "Viviana Luccioli"
  favicon: "images/v.png"
  navbar:
    left:
      - href: index.qmd
        text: Home

      - text: "Projects"
        menu:
          - text: "Georgetown: Data Science & Analytics (DSAN 5000)"
            href: projects/dsan-5000/_site/index.html
          - text: "Georgetown: Probabilistic Modeling & Statistical Computing (DSAN 5100)"
            href: projects/dsan-5100/_site/index.html
          - text: "UVA: Global Public Health Capstone Thesis"
            href: projects/GPH-capstone/GPH_capstone.html
    right:
      - href: "https://www.linkedin.com/in/viviana-luccioli-45a997207/"
        icon: linkedin
      - href: "mailto:viviluccioli@gmail.com"
        icon: envelope
      - href: "https://github.com/viviluccioli"
        icon: github

format:
  html:
    theme: cosmo
    css: styles2.css
    toc: true



